=== merus/SEP/WebContent/WEB-INF/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uts.edu.au/SEP" xmlns="http://www.uts.edu.au/SEP"
	elementFormDefault="qualified">

	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][A-Za-z'-]+( [A-Z][A-Za-z'-]+)*" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="date">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="email">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="password">
		<xs:restriction base="xs:string">
			<xs:pattern value=".{8,}" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="id">
		<xs:restriction base="xs:int">
			<xs:pattern value="[0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="authors">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="author" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="name" />
							<xs:element name="email" type="email" />
							<xs:element name="password" type="password" />
							<xs:element name="dob" type="date" />
							<xs:element name="biography" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="id" type="id" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== merus/SEP/SEP/WebContent/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<authors xmlns="http://www.uts.edu.au/SEP"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uts.edu.au/SEP users.xsd"> 
	<author id="11433099">
		<name>Tim Gee</name> 
		<email>tim@gee.com</email>
		<password>password</password>
		<dob>16/11/1990</dob>
		<biography>Work at this news place</biography>
	</author>
	<author id="92933738">
		<name>John Smith</name>
		<email>smithy@gmail.com</email>
		<password>smithyrulz</password>
		<dob>11/8/1970</dob>
		<biography>I am smithy</biography>
	</author>
	<author id="38392928">
		<name>Ronald McDonald</name>
		<email>ron@maccas.com</email>
		<password>hamberger</password>
		<dob>11/3/1920</dob>
		<biography>Eat my food, it's great</biography>
	</author>
	<author id="88549237">
		<name>Ying Octopus</name>
		<email>ying.octapus@gmail.com</email>
		<password>squid1963</password>
		<dob>21/8/1901</dob>
		<biography>Loves anything to do with squids and octopus</biography>
	</author>
</authors>
